name: OriginSpawn
version: '${version}'
main: click.seichi.originspawn.OriginSpawn
commands:
  originspawn:
    description: This is a spawn command beyond multiple worlds.
    usage: See /originspawn help.
permissions:
  originspawn.spawn:
    default: true
  originspawn.admin:
    default: op
