name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/*.yml
      - "!.github/workflows/cd.yml"
      - LICENSE
      - README.md
      - renovate.json
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java & Gradle
        uses: ./.github/actions/setup
      - name: Bump version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: releaseVersion
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jar
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: ./build/libs/*.jar