name: CD
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/*.yml
      - "!.github/workflows/cd.yml"
      - LICENSE
      - README.md
      - renovate.json
jobs:
  bump-and-build:
    name: Bump version and build jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java & Gradle
        uses: ./.github/actions/setup
      - name: Bump version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: releaseVersion
      - name: Git as GitHub Actions Bot
        uses: Lucky3028/git-as-gha@v1.0.1
      - name: Push changes
        run: git push --follow-tags
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jar
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: ./build/libs/*.jar