name: CI and CD
on:
  push:
    paths-ignore:
      - .github/workflows/*.yml
      - "!.github/workflows/ci-and-cd.yml"
      - LICENSE
      - README.md
      - renovate.json
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: chmod +x ./gradlew && ./gradlew jar
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: ./build/libs/*.jar